carRentalHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('cars/', include('cars.urls')),
    path('rentals/', include('rentals.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path
from .views import CarListView, CarCreateView, CarDeleteView, CarUpdateView, CarDetailView

app_name = 'cars'

urlpatterns = [
    path('', CarListView.as_view(), name='car-list'),
    path('create/', CarCreateView.as_view(), name='car-create'),
    path('<int:pk>/', CarDetailView.as_view(), name='car-detail'),
    path('<int:pk>/update/', CarUpdateView.as_view(), name='car-update'),
    path('<int:pk>/delete/', CarDeleteView.as_view(), name='car-delete'),
]

common/urls.py
from django.urls import path
from common.views import HomeView, AddReviewView, DashboardView

app_name = 'common'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('cars/<int:pk>/review/', AddReviewView.as_view(), name='add-review'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
]

rentals/urls.py
from django.urls import path

from rentals.views import RentalListView, RentalDetailView, RentalCreateView, RentalUpdateView, RentalDeleteView

app_name = 'rentals'
urlpatterns = [
    path('', RentalListView.as_view(), name='list'),
    path('<int:pk>/', RentalDetailView.as_view(), name='detail'),
    path('create/', RentalCreateView.as_view(), name='create'),
    path('<int:pk>/update/', RentalUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', RentalDeleteView.as_view(), name='delete'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Gogulanov-AUTO</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'common:home' %}"><b>Gogulanov-AUTO</b></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:home' %}">Home</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'cars:car-list' %}">Cars</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'rentals:list' %}">Rented cars</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:dashboard' %}">Dashboard</a>
                </li>


            </ul>
        </div>
    </div>
</nav>

<div class="container mt-4">
    {% block content %}{% endblock %}
</div>

<footer class="bg-dark text-white text-center p-3 mt-4">
    2026 Car Rental Hub - Martin Gogulanov
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>